ALTER TABLE book_info ADD COLUMN imageUrl VARCHAR(500) DEFAULT NULL AFTER publisher_id;
SET SQL_SAFE_UPDATES = 0;
UPDATE user 
SET password = '$2a$10$WTYqHSRgbvup3adumW4tGO4ljXZbVC4/W/IZpVrT7QKhUBuaL1BRO';
SET SQL_SAFE_UPDATES = 1;